import json
from pathlib import Path
R=Path(__file__).resolve().parents[3];A=Path(__file__).resolve().parent
J=lambda p:json.loads(p.read_text())
def dump(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
prior=R/'audit/fluent-revision/2026-09-17-genesis-source-1-10/open-issues.json';issues=J(prior)
for i in issues['items']:
 if i['id']=='G01':i.update(status='ALL_VERSES_SELF_REVIEWED_WITH_OPEN_ISSUES',action='Genesis 1–50, all 1533 public verses, now has fresh source comparison across the 1–10 and 11–50 passes. The word display was simplified Hebrew with targeted pointed-source checks, not a complete independent philological audit. Resolve logged semantic questions before closing F01.')
 if i['id']=='G08':i['action']='All 33 verses in Genesis 49 were compared in the 11–50 pass. Complete specialist lexical/syntactic review of the poem, especially 5, 10, 12, 14, 21–26, and then test poetry layout and read-aloud rhythm; do not equate verse comparison with final resolution.'
new=[
('G16','Genesis 17:12','F01/F03','Review whether the relative not of your descendants refers to the purchased household member or to the foreigner. The current English attaches it to foreigners. Obtain a supported syntactic decision before changing the main text.'),
('G17','Genesis 27:4,19,25,31','F01/F02/F05','Assess whether heartfelt blessing adds emotional content to nefesh as the blessing self. The current note discloses the rendering; preserve the fourfold refrain when deciding.'),
('G18','Genesis 29:10; 32:1; 39:3; 48:16','F02/F04/F05','During continuous reading assess the compressed mother’s-brother repetition, messenger/angel choice across scenes, and succeed in his hands idiom. Functional repetition and contextual accuracy take priority over either a uniform-word rule or a variation quota.'),
('G19','Genesis 34:27 and note v05,13,27; 37:28','F01/F03/F04','Review active plural agency versus English passives. Genesis 34:27 has they defiled; its note currently describes Shechem’s act without flagging the plural. Genesis 37:28 passivizes the disputed sale agents. Decide whether notes and pronouns preserve enough of the source without resolving uncertainty by assertion.'),
('G20','Genesis 36:26; 37:36','F01/F03/F11','Dishan and Medanites now follow the actual pinned Masoretic source, with notes disclosing name tensions. Independent textual review must assess these author decisions and any supported alternate reading; do not silently restore harmonized names.'),
]
for id,scope,criterion,action in new:issues['items'].append(dict(id=id,scope=scope,criterion=criterion,action=action,status='OPEN_INDEPENDENT_CHECK_PENDING' if id=='G20' else 'OPEN'))
issues['supersedes']=str(prior.relative_to(R));dump(A/'open-issues.json',issues)
reg=J(R/'EDITORIAL_PROGRESS.json');reg['base_checkpoint_version']=100
for b in reg['books']:
 if b['book']=='genesis':b.update(fresh_source_review='GENESIS_1_50_SELF_REVIEW_COMPLETE_WITH_OPEN_ISSUES',source_reviewed_chapters=list(range(1,51)),source_reviewed_verses=1533,targeted_additional_verses=0)
reg['active_block'].update(status='IN_PROGRESS',completed_pass='Apparatus for all 50 chapters; fresh verse-by-verse source comparison for all 50 chapters, with open issues',source_reviewed_chapters=list(range(1,51)),source_reviewed_verses=1533,current_targeted_additional_source_records=0,current_source_review_report=str(A.relative_to(R))+'/Genesis-Source-Review.md',issues=str(A.relative_to(R))+'/open-issues.json',next_source_chapter=None,full_bilingual_review_complete=False)
reg['active_block']['prior_priority_source_records']=15
reg['next_action']='Complete Genesis continuous reading, specialist questions and remaining F01–F12 criteria from the current issue register. All 50 chapters now have source self-review; do not repeat that pass or claim final approval. Then continue subsequent blocks without routine approval.'
reg['criteria_status']['F01']='ALL_GENESIS_VERSES_SELF_REVIEWED_WITH_OPEN_ISSUES; OTHER_BOOKS_PENDING';reg['criteria_status']['F10']='CURRENT_RECHECK_REQUIRED';dump(R/'EDITORIAL_PROGRESS.json',reg)
c=J(A/'corrections.json')
lines=['# Fluent: Genesis source review through chapter 50','', 'Date: 17 September 2026. Status: editorial draft; independent review pending.','', '**This batch compared Genesis 11–50: 40 chapters and 1,266 verses.** Together with the earlier 1–10 pass, all 50 Genesis chapters and 1,533 public verse records now have fresh source self-review. Nine Scripture verses were corrected in seven chapter files; one note was added and one revised.','', 'The main comparison used an aligned, simplified Hebrew word display and the current Fluent text. Pointed source records were revisited for the correction targets, and the source annotation inventory was inspected. This is an author/model review, not independent Hebrew certification, a complete critical-apparatus evaluation, or a completed whole-book reading test.','', '## Changes','', '| Passage | Correction |','|---|---|']
for v in c['verse_changes']:lines.append('| '+v['reference']+' | '+v['rationale']+' |')
lines += ['', 'The new Genesis 36:26 note identifies the received Dishan reading without harmonizing it to Dishon. The revised Genesis 37:28,36 note distinguishes Ishmaelites, Midianites and Medanites and keeps the identity of the sellers in verse 28 open. Names were checked against the supplied Hebrew source itself, not inferred from a familiar English version.','', '## Evidence and coverage','', 'The bound source remains OSHB/WLC at commit `6a5db284c715c18b239422e57bb89684e6a19f00`. Each of the 1,266 review records preserves the exact XML verse, source hash, previous and current English, decision and chapter-specific observations. Public Genesis 31:55 maps to Hebrew 32:1; public 32:1–32 maps to Hebrew 32:2–33. No source verse was dropped or double-counted.','', 'The earlier 267-verse review, its six Scripture changes and its targeted question evidence remain preserved at their historical checkpoint. The 15 previously targeted verses are now included within the full 11–50 coverage and are not added again to the 1,533-verse total.','', 'Genesis 49 was read in full against the source. Its disputed poetry, including Shiloh and verses 21–26, remains provisional. Narrative repetition, repeated speeches, genealogical numbers, gendered relationships, divine titles and the sequence of actions were checked without imposing a required percentage of difference from TSW.','', '## Still required','', '- Resolve the current G01–G20 issue register, including older unresolved questions. This batch adds explicit checks for Genesis 17:12, the repeated heartfelt blessing wording, messenger/angel terminology, and agency in Genesis 34:27 and 37:28.', '- Complete continuous whole-book reading, paragraph/headings and poetry presentation checks, and the remaining note/vocabulary and house-style decisions.', '- Obtain qualified independent language review and reader testing, reconcile the Companion, and secure final editorial approval. No final-compliance claim is made.','', 'The next action is the remaining Genesis editorial work. Routine continuation already has authorization. The drafting automation stays paused.','', '## Verification','', 'See verification.json for the fresh structural result. The verifier checks all 145 ledgers against their bound sources, exact Scripture and note changes, cumulative 1,189 chapters and 31,083 public verse records, and preservation of original evidence. These checks validate structure and traceability, not editorial judgment. TSW and Companion are unchanged. No new corpus-wide similarity percentage is claimed.','']
(A/'Genesis-Source-Review.md').write_text('\n'.join(lines))
