"""Apply the reviewed source/fluency decisions after checkpoint 99."""
import copy,hashlib,json,re,subprocess,sys
from pathlib import Path
from difflib import SequenceMatcher
R=Path(__file__).resolve().parents[3];A=Path(__file__).resolve().parent
BASE='7caadac15c6cc7c76534069dd1d7d936d98f69a1';S=Path(sys.argv[1]);sha=lambda b:hashlib.sha256(b).hexdigest()
sys.path.insert(0,str(R/'tools'))
from audit_translation_overlap import verse_texts,words

def dump(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def old(p):return subprocess.check_output(['git','show',BASE+':'+p],cwd=R)
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()==BASE
E={
'Genesis 1:14':('Let them mark signs, appointed times, days, and years.','Let them serve as signs and mark appointed times, days, and years.','F01/F02','The lights are to be signs (le-otot), not to mark signs. Give the sign function natural English while retaining the appointed times, days and years.'),
'Genesis 1:26':('in our image, to bear our likeness.','in our image, in our likeness.','F01/F03','Ke-dmutenu describes likeness. Remove the purpose construction to bear, which can suggest an additional stated purpose; retain image and likeness as distinct expressions.'),
'Genesis 2:5':('no shrub of the field had yet appeared on the earth, and no plant of the field had sprouted. The LORD God had not sent rain on the earth, and there was no human to work the ground.','no shrub of the field had yet appeared on the earth, and no plant of the field had sprouted, because the LORD God had not sent rain on the earth and there was no human to work the ground.','F01/F02','Make the explicit ki connection audible: the lack of rain and a human cultivator explains the preceding situation. The sentence still continues the temporal clause in 2:4.'),
'Genesis 2:10':('Beyond it, the river divided into four branches.','From there, the river divided into four branches.','F01/F02','U-misham means and/from there. Avoid specifying beyond the garden where the source gives a less specific deictic expression.'),
'Genesis 5:32':('After Noah reached 500 years of age, he became the father of Shem, Ham, and Japheth.','Noah was 500 years old, and he became the father of Shem, Ham, and Japheth.','F01/F03','Preserve the age statement and coordinated fatherhood statement without adding after. Do not harmonize the wording to a calculated chronology or imply that the three births were simultaneous.'),
'Genesis 7:24':('The waters held their power over the earth for 150 days.','The waters continued to overwhelm the earth for 150 days.','F02/F04','Render the continuing force of gavar al naturally; retain the water subject, its prevailing force over the earth and the exact duration. The same root remains prominent in 7:18–20.')}
changes={};vchanges=[]
for ref,(before,after,crit,reason) in E.items():
 ch,num=map(int,ref.split()[1].split(':'));p=f'translations/fluent/OT/genesis/Genesis_{ch:02}.md';t=(R/p).read_text();vs=verse_texts(t);label=f'{num:02}';assert vs[label].count(before)==1
 if p not in changes:changes[p]=dict(path=p,chapter=ch,before_sha256=sha(old(p)),reasons=[])
 line=next(l for l in t.splitlines() if l.startswith(f'v{num:02}:'));assert before in line;t=t.replace(line,line.replace(before,after));(R/p).write_text(t);changes[p]['reasons'].append(reason)
 vchanges.append(dict(reference=ref,path=p,before=vs[label],after=verse_texts(t)[label],criteria=crit,rationale=reason))
qpath=R/'audit/fluent-revision/WORK_QUEUE.json';q=json.loads(qpath.read_text());affected=[]
for scope in q['completed_draft_scopes']:
 lp=R/scope['ledger'];l=json.loads(lp.read_text());hit=False
 for ch in l['chapters']:
  if ch['path'] not in changes:continue
  hit=True;rec=changes[ch['path']];assert ch['after_sha256']==rec['before_sha256'];rec['after_sha256']=sha((R/ch['path']).read_bytes());rec['ledger']=scope['ledger'];ch['after_sha256']=rec['after_sha256']
  for v in l['verses']:
   if v['reference'] not in E or int(v['reference'].split()[1].split(':')[0])!=ch['chapter']:continue
   edit=next(e for e in vchanges if e['reference']==v['reference']);assert v['after']==edit['before'];edit.update(source_reference=v['source_reference'],source_verse_sha256=v['source_verse_sha256'])
   v.setdefault('subsequent_editorial_changes',[]).append(dict(audit=str(A.relative_to(R))+'/corrections.json',base_commit=BASE,previous_after=v['after'],rationale=edit['rationale']))
   v['after']=edit['after'];v['identical_words_to_tsw']=words(v['after'])==words(v['tsw_comparator']);v['word_similarity_to_tsw']=round(SequenceMatcher(None,words(v['after']),words(v['tsw_comparator']),autojunk=False).ratio(),6)
  cp=R/'audit/exegetical-core/fluent-production/genesis'/(Path(ch['path']).stem+'_review.json');cr=json.loads(cp.read_text());cr['chapter_binding']=copy.deepcopy(ch);cv={v['reference']:v for v in l['verses']}
  for field in ['key_decisions','verse_decisions']:
   if field in cr:cr[field]=[copy.deepcopy(cv[v['reference']]) if v.get('reference') in E else v for v in cr[field]]
  cr.setdefault('subsequent_editorial_audits',[]).append(dict(audit=str(A.relative_to(R))+'/corrections.json',base_commit=BASE,previous_chapter_sha256=rec['before_sha256'],scope='Genesis 1–10 source/fluency comparison',editorial_status='REVIEW_PENDING'));dump(cp,cr)
 if hit:
  affected.append(scope['ledger']);l.setdefault('subsequent_editorial_audits',[]).append(dict(audit=str(A.relative_to(R))+'/corrections.json',base_commit=BASE,scope='Genesis 1–10 source/fluency comparison',editorial_status='REVIEW_PENDING'));dump(lp,l)
# Record reviewed passages with specific observations; not a lexical certification.
observations={
1:[(1,2,'Independent opening retained alongside its temporal alternative in the note; unformed/empty and ruach alternatives retained.'),(3,13,'Creation commands, fulfilment, good judgments, naming, numbered days and repeated evenings/mornings checked.'),(14,19,'Light functions, two great lights, separate stars clause and day/night/light/dark contrasts checked; the signs clause corrected.'),(20,25,'Water creatures, birds, livestock and crawling/wild categories, kinds, blessing and multiplication checked without modern taxonomy.'),(26,31,'Image/likeness, collective humanity, singular/plural movement, male/female, dominion, food allocation and very good checked; purpose wording removed in v26.')],
2:[(1,4,'Seventh-day completion/rest and the account formula retained; the reversal earth/heaven and transition into the garden remain visible.'),(5,7,'Rain/cultivation explanation and uncertain ed checked; ki made explicit; dust, nostrils, breath and living being distinguished.'),(8,14,'Planting and tree descriptions, four rivers, direction and materials compared; from there restored without speculative locations.'),(15,20,'Work/guard, eating permission/prohibition, emphatic death and ezer kenegdo checked; no inferred inferiority or altered creature order.'),(21,25,'Sleep, side/rib, building, ish/ishah wordplay, kinship, one flesh and nakedness checked; alternatives remain in the notes.')],
3:[(1,7,'Serpent and woman speech remain distinct; touching is not inserted into the earlier divine prohibition; knowledge, seeing, eating and husband with her checked.'),(8,13,'Sound/voice and breeze, hiding, questions, admissions and blame exchange compared without added motives.'),(14,19,'Cursing, dust, offspring, same strike verb, pain/pregnancy, desire/rule and ground/labor/return checked; consequential ambiguities remain noted.'),(20,24,'Eve naming, garments, plural one of us, interrupted preventive speech, expulsion and guarded access checked. Lest in v22 remains a fluency question, not silently replaced by a completed speech.')],
4:[(1,7,'Know idiom, Cain wordplay, offerings, regard, fallen face and sin/desire/rule checked; reasons for differential regard are not supplied.'),(8,16,'Cain speech gap, murder, guard question, blood, curse, guilt/punishment, sign and wandering checked; no invented speech or mark description.'),(17,22,'Names, descent, city-building and occupations compared, including Mehujael/Methushael distinction and difficult metalworking phrase.'),(23,26,'Lamech parallelism and 7/77 vengeance, Seth naming, replacement offspring and Enosh/calling formula checked; verbal alternatives remain noted.')],
5:[(1,5,'Adam/humanity, image/likeness and male/female opening checked; Adam ages 130/800/930 and death formula compared.'),(6,20,'Seth 105/807/912, Enosh 90/815/905, Kenan 70/840/910, Mahalalel 65/830/895 and Jared 162/800/962 checked individually against the Hebrew.'),(21,27,'Enoch 65/300/365 and walking/taking instead of death formula checked; Methuselah 187/782/969 checked.'),(28,32,'Lamech 182/595/777 and Noah name/relief checked. Noah age 500 remains an age statement coordinated with three-son introduction, with added after removed.')],
6:[(1,4,'Multiplication, sons of God, human daughters, disputed spirit verb, 120 years and Nephilim/mighty ones compared without resolving identity questions.'),(5,8,'Human evil emphasis, regret, grief, wipe-out announcement and Noah favor checked.'),(9,13,'Noah account/righteousness/walking, sons, corrupt/destroy root and violence/all-flesh language checked.'),(14,16,'Wood, compartments, pitch and 300/50/30 cubits compared. Roof/opening and cubit geometry remain unresolved rather than declared a recovered construction plan.'),(17,22,'Flood, breath/life, covenant, household, animal pairs, male/female, arrival, food and doubled obedience statements checked.')],
7:[(1,5,'Righteousness, household, seven-seven clean pairs, unclean pair, birds, seven days and forty days/nights checked; counting alternative retained.'),(6,16,'Noah 600, entry parties, paired animals, seventh-day onset, month/day and deep/windows language checked. Repeated entry accounts and God/LORD designations preserved.'),(17,20,'Flood duration, lifting ark, increasing/prevailing water, all high mountains and fifteen cubits compared without inventing a chronology.'),(21,24,'Death categories, nostril breath, dry land and Noah survivors checked. The first wiping verb is active in Hebrew, rendered passively in English; agency/voice retained as an open review question. Gavar al in v24 made idiomatic without changing 150 days.')],
8:[(1,5,'Remembering/wind, closure, decreasing water, 150 days and seventh/tenth-month dates checked; Ararat remains plural mountains.'),(6,12,'Window, raven back-and-forth, dove rest, leaf, and separate seven-day intervals compared without collapsing them.'),(13,19,'601st year and first/second-month dry-land dates, departure command and fulfilment, and families compared. 8:17 ketiv/qere imperative inspected; both concern bringing out, with no second action added.'),(20,22,'Clean offerings, aroma, inner speech, never-again promises, ki alternative and four paired earth rhythms checked.')],
9:[(1,7,'Blessing, fear, food, blood/life and accounting checked; compact human-blood saying kept without importing a judicial procedure.'),(8,17,'Covenant participants, descendants, all living creatures, repeated all-flesh language, flood promise and bow/remembering checked.'),(18,24,'Sons and Canaan identifiers, farmer/vineyard wording, intoxication, nakedness, backward covering and younger/youngest alternative checked; 9:20 ambiguity retained for further review.'),(25,29,'Canaan curse, blessing to LORD, slave/slaves, plural their, ambiguous he in v27 and Noah 350/950 checked.')],
10:[(1,7,'Japheth and Ham descendant lists checked name by name; Dodanim follows this Hebrew text, and Mizraim remains an ancestral name.'),(8,14,'Nimrod/hunter, cities, possible Asshur subject, great-city referent, peoples and Philistine parenthesis checked without harmonization.'),(15,20,'Canaan descendants, boundaries and repeated clans/languages/lands/nations formula checked.'),(21,25,'Shem/Japheth age ambiguity, Elam/Asshur/Arpachshad descendants and Peleg division checked; alternative in note retained.'),(26,32,'Joktan descendants, Mesha/Sephar settlement range and concluding language/territory/descent formulas checked.')]
}
source=(S/'genesis-pinned-source.xml').read_bytes();s=source.decode();records=[]
for ch in range(1,11):
 p=f'translations/fluent/OT/genesis/Genesis_{ch:02}.md';before=verse_texts(old(p).decode());after=verse_texts((R/p).read_text())
 for label in before:
  n=int(label);ref=f'Genesis {ch}:{n}';m=re.search(r'<verse\b[^>]*osisID="Gen\.'+str(ch)+r'\.'+str(n)+r'"[^>]*>.*?</verse>',s,re.S);assert m
  observation=next(o for a,b,o in observations[ch] if a<=n<=b)
  records.append(dict(reference=ref,path=p,before=before[label],after=after[label],exact_source_record=m[0],source_verse_sha256=sha(m[0].encode()),decision='REVISE' if ref in E else 'RETAIN_WITH_REVIEW_LIMITS',observation=observation,rationale=E[ref][3] if ref in E else None,independent_review='PENDING'))
assert len(records)==267
dump(A/'source-review.json',dict(base_commit=BASE,source_file='genesis-pinned-source.xml',source_file_sha256=sha(source),source_commit='6a5db284c715c18b239422e57bb89684e6a19f00',scope='Genesis 1–10, every verse compared; author/model self-review, not independent philological certification',chapters=10,verses=267,full_genesis_review_complete=False,records=records))
dump(A/'corrections.json',dict(base_commit=BASE,chapters=list(changes.values()),verse_changes=vchanges,affected_ledgers=affected,publication_allowed=False))
q.setdefault('completed_editorial_passes',[]).append(dict(scope='Genesis 1–10 source comparison, 267 verses',status='SELF_REVIEW_COMPLETE_WITH_OPEN_ISSUES',report=str(A.relative_to(R))+'/Genesis-Source-Review.md',independent_editorial_review='REVIEW_PENDING',publication_allowed=False))
q['next_work'][0]['action']='Genesis 1–10 now has fresh verse-by-verse self-review with open issues. Continue at Genesis 11, finish the remaining Genesis source/continuous-reading work and documented questions, then subsequent 50-chapter blocks without routine approval. Read EDITORIAL_PROGRESS.json and the latest source-review report.'
dump(qpath,q)
print(json.dumps(dict(changed_chapters=len(changes),changed_verses=len(vchanges),reviewed_verses=len(records),affected_ledgers=len(affected))))
