import hashlib,json,re,sys
from pathlib import Path
R=Path(__file__).resolve().parents[3];A=Path(__file__).resolve().parent;S=Path(sys.argv[1]);sha=lambda b:hashlib.sha256(b).hexdigest()
def dump(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
s=(S/'genesis-pinned-source.xml').read_text();refs=[(24,50),(31,24),(31,29),(35,7),(38,15),(38,16),(38,20),(38,21),(38,22),(38,24),(44,20),(44,21),(44,22),(44,30),(44,31)];records=[]
for ch,n in refs:
 m=re.search(r'<verse\b[^>]*osisID="Gen\.'+str(ch)+r'\.'+str(n)+r'"[^>]*>.*?</verse>',s,re.S);assert m
 p=R/f'translations/fluent/OT/genesis/Genesis_{ch:02}.md';line=next(l for l in p.read_text().splitlines() if l.startswith(f'v{n:02}:'))
 records.append(dict(reference=f'Genesis {ch}:{n}',exact_source_record=m[0],source_verse_sha256=sha(m[0].encode()),fluent=line,scope='targeted question and local context only'))
sources=[dict(id='NET31',title='NET translators’ notes, Genesis 31:24 and 29',url='https://www.biblegateway.com/passage/?search=Genesis+31&version=NET',accessed='2026-09-17',paraphrase='The translators acknowledge uncertainty and favor a restriction on blessing or cursing. This supports the plausibility of the existing pronouncement interpretation without proving it uniquely correct.'),dict(id='NET38',title='NET translators’ note, Genesis 38:21',url='https://www.biblegateway.com/passage/?search=Genesis+38%3A21-22&version=NET',accessed='2026-09-17',paraphrase='The note favors a cultic role for qedeshah. It does not provide the contrary specialist analysis needed to settle the existing open question about shrine language.'),dict(id='NET44',title='NET translators’ notes, Genesis 44:22',url='https://www.biblegateway.com/passage/?search=Genesis+44&version=NET',accessed='2026-09-17',paraphrase='The translators identify Jacob as the referent of he and construe the final verbs as a conditional sequence. This corroborates the existing fluent English choice; its note still preserves the alternative.')]
dump(A/'priority-review.json',dict(scope='15 additional source records; no entire additional chapter credited',source_file='genesis-pinned-source.xml',source_file_sha256=sha((S/'genesis-pinned-source.xml').read_bytes()),records=records,external_sources=sources,decisions=[dict(issue='G04',status='AUTHOR_DECISION_RETAIN_WITH_ALTERNATIVE',action='Retain the existing pronouncement wording in 31:24,29 and its broader alternative note. The wording has a documented linguistic interpretation; absence of a separate noun in Hebrew does not by itself invalidate an idiomatic rendering. Independent review remains pending.',evidence=['Genesis 24:50','Genesis 31:24','Genesis 31:29','NET31']),dict(issue='G05',status='OPEN',action='Retain the source-grammar note and current singular English pending a broader treatment of plural agreement with Elohim; a single-verse inspection does not settle the referent.',evidence=['Genesis 35:7']),dict(issue='G06',status='OPEN',action='Retain current wording provisionally. The available translator note favors the cultic interpretation; obtain specialist evidence addressing the contrary case before deciding whether shrine is too specific.',evidence=['Genesis 38:15','Genesis 38:16','Genesis 38:20','Genesis 38:21','Genesis 38:22','Genesis 38:24','NET38']),dict(issue='G07',status='AUTHOR_DECISION_RETAIN_WITH_ALTERNATIVE',action='Retain father in 44:22: the later appeal in 44:30–31 explicitly links the father’s death to the young man’s absence. The existing note discloses the supplied referent and the alternative; no unnecessary pronoun ambiguity is introduced into Fluent.',evidence=['Genesis 44:20','Genesis 44:21','Genesis 44:22','Genesis 44:30','Genesis 44:31','NET44'])],independent_review='PENDING'))
prior=R/'audit/fluent-revision/2026-09-17-editorial-genesis/open-issues.json';issues=json.loads(prior.read_text())
for item in issues['items']:
 if item['id']=='G01':item['action']='Genesis 1–10 (267 verses) now has fresh verse-by-verse self-review with open findings. Complete Genesis 11–50, then resolve all logged questions before closing source fidelity.';item['status']='IN_PROGRESS'
 if item['id'] in ['G04','G07']:
  item['status']='AUTHOR_DECISION_RECORDED_INDEPENDENT_REVIEW_PENDING';item['decision_evidence']=str(A.relative_to(R))+'/priority-review.json'
issues['items'] += [dict(id='G12',scope='Genesis 3:22',criterion='F02/F03',action='Evaluate a contemporary replacement for lest that preserves the preventive force and interrupted subordinate clause without inventing a completed speech.',status='OPEN'),dict(id='G13',scope='Genesis 6:16',criterion='F01/F03',action='Review the roof/light-opening term and cubit construction with specialist evidence; present geometry is provisional and must not be treated as a recovered blueprint.',status='OPEN'),dict(id='G14',scope='Genesis 7:23',criterion='F01/F04',action='Evaluate whether to restore the Hebrew active wiping verb before the passive repetition without supplying an unwarranted explicit agent.',status='OPEN'),dict(id='G15',scope='Genesis 9:20',criterion='F01/F03',action='Reassess whether began to work the ground overdetermines the compact farmer/begin/plant wording. The existing note preserves the alternative; a fresh lexical/syntactic decision remains open.',status='OPEN')]
issues['supersedes']=str(prior.relative_to(R));dump(A/'open-issues.json',issues)
reg=json.loads((R/'EDITORIAL_PROGRESS.json').read_text());reg['base_checkpoint_version']=99
for b in reg['books']:
 if b['book']=='genesis':b['fresh_source_review']='GENESIS_1_10_SELF_REVIEW_COMPLETE_WITH_OPEN_ISSUES';b['source_reviewed_chapters']=list(range(1,11));b['source_reviewed_verses']=267;b['targeted_additional_verses']=15
reg['active_block'].update(status='IN_PROGRESS',completed_pass='Apparatus scope for all 50; fresh source comparison for chapters 1–10',source_reviewed_chapters=list(range(1,11)),source_reviewed_verses=267,current_targeted_additional_source_records=15,current_source_review_report=str(A.relative_to(R))+'/Genesis-Source-Review.md',issues=str(A.relative_to(R))+'/open-issues.json',next_source_chapter=11)
reg['active_block']['prior_apparatus_targeted_source_records']=reg['active_block'].pop('targeted_source_records')
reg['active_block']['prior_apparatus_targeted_genesis_verse_records']=reg['active_block'].pop('targeted_genesis_verse_records')
reg['next_action']='Continue the fresh source comparison at Genesis 11. Finish Genesis 11–50, continuous reading and open questions before marking the 50-chapter block complete. No routine batch approval needed.'
reg['criteria_status']['F01']='IN_PROGRESS; GENESIS_1_10_SELF_REVIEWED_WITH_OPEN_ISSUES';reg['criteria_status']['F10']='CURRENT_RECHECK_REQUIRED';dump(R/'EDITORIAL_PROGRESS.json',reg)
